#!/bin/bash
#
# Sample for gl-common.bash
#
# CC0 - Public Domain, jeremy.walther@golflima.net
# To the extent possible under law, Jérémy Walther has waived
# all copyright and related or neighboring rights to this file.
# This work is published from: France.
# See: <https://creativecommons.org/publicdomain/zero/1.0/deed>
#
# Feel free to use it as you want.
#
# This sample is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# Load gl-common.bash
. ../gl-common.sh SAMPLE_SPINNER
if [[ $? > 0 ]]; then echo "Error when loading file '../gl-common.sh'"; exit 1; fi

echo "call this script with a flag -t, --test, or nothing"
echo
echo "has_option()"
has_option "t" $@ && echo "'-t' found"
has_option "test" $@ && echo "'--test' found"
has_option "t/test" $@ && echo "'-t' or '--test' found"
echo
echo "get_option()"
echo "value of '-t' : '$(get_option 't' $@)'"
echo "value of '--test' : '$(get_option 'test' $@)'"
echo "value of '-t' or '--test' : '$(get_option 't/test' $@)'"
echo
echo "has_option_wf()"
has_option_wf "t" $@ && echo "'-t' found"
has_option_wf "t" $@ && echo "'-t' found"
has_option_wf "test" $@ && echo "'--test' found"
has_option_wf "test" $@ && echo "'--test' found"
# has_option_wf "t/test" $@ && echo "'-t' or '--test' found"
# has_option_wf "t/test" $@ && echo "'-t' or '--test' found"
